// Generated by CodiumAI
import { render, screen } from '@testing-library/react';
import ProductCard from './product-card';

const product = { asin:'123456', title: 'Test Product', price: 10, description: 'Test Description', thumbnail: 'https:\/\/m.media-amazon.com\/images\/I\/81C2s8WfgFL._AC_UL320_.jpg' };

describe('ProductCard', () => {

  // Verrificar renderizados de product name, description, y price
  it('should render the product name, description, and price', () => {
    render(<ProductCard product={product} />);
    expect(screen.getByText('Test Product')).toBeInTheDocument();
    expect(screen.getByText('Test Description')).toBeInTheDocument();
    expect(screen.getByText('$ 10')).toBeInTheDocument();
  });

  // Verificar que esta el boton de Add to cart y que tiene ese texto 
  it('should display a button to add the product to the cart', () => {
    render(<ProductCard product={product} />);
    expect(screen.getByRole('button', { name: 'Add to cart' })).toBeInTheDocument();
  });
});
